### ISSUE TITLE
List comprehension with conditions does not work

### ISSUE THREAD

**Issue by caioariede** [chrivers/pyjaco#69]
First, thank you guys, this project is awesome! :)

I found that..
# Given:

``` python
[x for x in (1, 2, 3, 4) if (x % 2) == 0]
```
# We expect:

``` python
[2, 4]
```
# But what we get is:

``` python
[1, 2, 3, 4]
```

**Comment by chrivers** [comment]
Thank you for the kind words - it's always nice to know that people enjoy what we do :-)

And thanks for reporting this bug. I assume you're using HEAD from chrivers/pyjaco? If not, please try that. And in any case, can you please attach the resulting JS code? Thank you very much.

**Comment by chrivers** [comment]
(It is very possible that this is a bug, because list comprehension is one area where we don't have 100% support)

**Comment by caioariede** [comment]
I tried with http://pyjaco.org/demo (not HEAD)

Using trunk I got the result I expected :)

Thanks!
