### ISSUE TITLE
Distributing js library with pypi package

### ISSUE THREAD

**Issue by dusty-phillips** [chrivers/pyjaco#7]
As I understand it, the py-builtins.js library is an integral part of any javascript compiled with pyjaco. Therefore, this file should be distributed with, or buildable from the python binary distribution shipped via setup.py.

As discussed in http://stackoverflow.com/questions/4519127/setuptools-package-data-folder-location there are essentially two ways to ship data files with setup.py; `package_data` and `data_files`. The problem with `package_data` is that the data file must be distributed inside the pyjaco library. The problem with `data_files` is that it is impossible to reliably determine the location of the installed file from inside the python code across operating systems and virtualenvs.

I see the following options:
- move the `library` directory to `pyjaco/jslib` or similar and ship the various `##-*.js` files in `package_data`. Then merge the `generate_library.py` script into `pyjs.py` so that the script can generate the complete library for users.
- leave `library` where it is, but when `setup.py` is run, ensure that `pyjaco/jslib` exists and generate `py-builtins.js` into that directory before calling setup. Then ship `py-builtins.js` as part of `package_data`.
- assume that `py-builtins.js` has been generated at the time that `setup.py` is run and include the script in `data_files`. Then create fragile code that attempts to guess where the file was installed. This fragile code is guaranteed not to work on all possible platforms, buildouts, or virtualenvs.

I am willing to implement either of the first two options. I have a preference for the first option because it means that only files that are included in version control are shipped with the distribution; py-builtins.js is generated from these files instead of being shipped directly. No setup.py hack is required to ensure that the data has been generated. I didn't want to start moving directories around without your blessing, though, so I'll await feedback on this issue before developing anything.

**Comment by chrivers** [comment]
Regarding the first solution, isn't there some way to include library in package_data? I'm not very familiar with the pypi packaging. I'm all for merging generate_library into the pyjs.py file. Especially with an improvement where pyjs.py will check if the newest mtime for a library/*.js file is newer than the py-builtins.py file, and generate it only in that case. That would be very nice :)

For now, let's stick to the name py-builtins.js, but pending discussion on the mailing list, we will probably find another name soon. That shouldn't affect the change here, though.

**Comment by dusty-phillips** [comment]
Yes it's possible to include the library in package_data using the first solution. I'm sorry I worded it the way I did, what I meant is that the library directory has to be moved inside the pyjaco package directory in order for setup.py to pick it up and distribute it. I will do this on another branch to demonstrate. As I mentioned in a recent mailing list message, I'd eventually like to see setup.py as the main source of distribution, with debian (and other OS) packages generated from that.

**Comment by chrivers** [comment]
+1 for debian package using pypi. But do we really have to put javascript files in our python package dir? It seems so very dirty. Can't we at least move the python files one level in, so we have:

root/setup.py
root/src/library/..
root/src/pyjaco/..

or something like that? I'm really against mixing python and javascript into a python package, it seems wrong.

**Comment by chrivers** [comment]
After the discussion on the mailing list, and the merging of your recent patch, I believe this issue is closed. Have I missed anything?

**Comment by dusty-phillips** [comment]
Yes, PR #10 closes this issue.

**Comment by chrivers** [comment]
Cool, thanks. Just making sure :)
