### ISSUE TITLE
unobtrusive user defined prototype functions on arrays will break pyjaco standard library

### ISSUE THREAD

**Issue by obeleh** [chrivers/pyjaco#79]
I'm not sure how fixable this but can't find any previous posts about it.

this will fail:

//Prototype function to fix that IE doesn't have indexOf on array
//added in a different js file 
//https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Array/IndexOf
if (!Array.prototype.indexOf) {
    Array.prototype.indexOf = function (searchElement /*, fromIndex */ ) {
        "use strict";
        if (this == null) {
            throw new TypeError();
        }
        var t = Object(this);
        var len = t.length >>> 0;
        if (len === 0) {
            return -1;
        }
        var n = 0;
        if (arguments.length > 1) {
            n = Number(arguments[1]);
            if (n != n) { // shortcut for verifying if it's NaN
                n = 0;
            } else if (n != 0 && n != Infinity && n != -Infinity) {
                n = (n > 0 || -1) \* Math.floor(Math.abs(n));
            }
        }
        if (n >= len) {
            return -1;
        }
        var k = n >= 0 ? n : Math.max(len - Math.abs(n), 0);
        for (; k < len; k++) {
            if (k in t && t[k] === searchElement) {
                return k;
            }
        }
        return -1;
    }
}

//Generated code
var lst = list([$c1, $c2, $c3]);
if (bool(py_builtins.**not**(lst.PY$**contains**($c4))) === True) {
    py_builtins.print(str('ok'));
}

Message:
Line: 911
Error: Object doesn't support property or method 'PY$**eq**'

I think this is because the indexOf prototype function is copied over in the **inherit function. When the function __contains** is called it will then think that indexOf is an array member.

**Comment by chrivers** [comment]
This bug does not show up in the new branch, under V8 or spidermonkey. If you have time, could you test this under IE again? Marking as closed for now.
